import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { cn } from "@/utils/cn";
import { Headerbar } from "@/app/Headerbar";
import { AuthProvider } from "./AuthProvider";
import { getUserServerside } from "@/utils/getUserServerside";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserServerside();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme accentColor="green">
          <AuthProvider serverUser={user}>
            <Headerbar />
            <div className={cn("min-h-[90svh]", "w-full")}>{children}</div>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
